// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Stats.Lapack")>]
[<assembly: AssemblyProductAttribute("FSharp.Stats")>]
[<assembly: AssemblyDescriptionAttribute("F# project for statistical computing")>]
[<assembly: AssemblyVersionAttribute("0.0.13")>]
[<assembly: AssemblyFileVersionAttribute("0.0.13")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Stats.Lapack"
    let [<Literal>] AssemblyProduct = "FSharp.Stats"
    let [<Literal>] AssemblyDescription = "F# project for statistical computing"
    let [<Literal>] AssemblyVersion = "0.0.13"
    let [<Literal>] AssemblyFileVersion = "0.0.13"
    let [<Literal>] AssemblyConfiguration = "Release"
